---
- name: Execute Pacemaker Cluster Services Checks
  hosts: nodes
  become: yes
  tasks:
    - name: Include the  cluster Operations     
      include_role:
        name: pcs_cluster_operations
      vars:
        check_type: 'service_checks'

# - name: Execute Pacemaker Cluster Health Audit
#   hosts: nodeb
#   become: yes
#   tasks:
#     - name: Pacemaker Operations
#       block:
#         - name: Run Pacemaker Cluster Operations Role - Health Audit
#           ansible.builtin.include_role:
#             name: pcs_cluster_operations
#           vars:
#             type: 'cluster_checks'