---
- name: Pacemaker Cluster Health Check
  hosts: cluster_nodes  # MUST TARGET ALL NODES
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Initialize Health Check Error List
      set_fact:
        health_check_errors: []

  roles:
    - role: pacemaker_health_check