---
- name: Pacemaker Cluster Health Check
  hosts: cluster_nodes  # MUST TARGET ALL NODES
  become: true
  gather_facts: true
  ignore_errors: true

  roles:
    - pacemaker_health_check

  post_tasks:

    - name: Summary of errors across all nodes
      ansible.builtin.debug:
        msg: "Host {{ item }} {{ (hostvars[item]).get('health_check_errors', 'No Errors') }} "
      loop: "{{ ansible_play_hosts }}"
      run_once: true

    # -------------------------------------------------------
    # CONSOLIDATED REPORTING (Runs once on Localhost)
    # -------------------------------------------------------
    - name: "Generate and Display Cluster Report"
      run_once: true
      delegate_to: localhost
      block:
        # 1. Build the text report
        - name: Build Report String
          set_fact:
            final_report: |
              =============================================================
              PACEMAKER CLUSTER HEALTH REPORT
              =============================================================
              Timestamp: {{ ansible_date_time.iso8601 }}
              Total Nodes Checked: {{ ansible_play_hosts | length }}
              
              DETAILS BY NODE:
              {% for host in ansible_play_hosts %}
              -------------------------------------------------------------
              NODE: {{ host }}
              {% if ((hostvars[host]).get('health_check_errors')) | default([]) | length == 0 %}
              STATUS: [ OK ]
              {% else %}
              STATUS: [ FAILED ]
              ERRORS:
              {% for err in (hostvars[host]).get('health_check_errors') %}
                - {{ err }}
              {% endfor %}
              {% endif %}
              {% endfor %}
              =============================================================

        # 2. Determine Failure Status based on the Report Content
        - name: Set Cluster Failure Flag
          set_fact:
            cluster_has_failures: "{{ 'STATUS: [ FAILED ]' in final_report }}"

        # 3. Print the report to the Ansible Console
        - name: "PRINT CONSOLIDATED REPORT"
          debug:
            msg: "{{ final_report.split('\n') }}"

        # -------------------------------------------------------
        # FINAL FAILURE
        # -------------------------------------------------------
        - name: Fail Playbook if Critical Errors Exists
          fail:
            msg: "Cluster Health Check Failed. See the 'PRINT CONSOLIDATED REPORT' task above for details."
          when: cluster_has_failures | bool