---
- name: Pacemaker Cluster Health Check
  hosts: cluster_nodes  # MUST TARGET ALL NODES
  become: true
  gather_facts: true

  roles:
    # - pacemaker_health_check
    # - pacemaker_cluster_backup
      - pacemaker_event_cleanup