---
- name: Pacemaker Cluster Opertions
  hosts: pacemaker_cluster  # MUST TARGET ALL NODES
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: "Step: Determine Active Cluster Node"
      include_role:
        name: pacemaker_common
        tasks_from: elect_active_node
      run_once: true

    - name: "Validate Election Success"
      ansible.builtin.fail:
        msg: "No active cluster node could be determined. Aborting."
      when: active_cluster_node is not defined or active_cluster_node == ""

  roles:
    # - role: pacemaker_health_check

    # - role: pacemaker_cluster_backup
    #   when: inventory_hostname == active_cluster_node

    # - role: pacemaker_event_cleanup
    #   when: inventory_hostname == active_cluster_node
    
    # - role: pacemaker_verify
    #   when: inventory_hostname == active_cluster_node