---
- name: Set Pacemaker Cluster Resource State
  hosts: cluster_nodes
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: "Step: Determine Active Cluster Node"
      include_role:
        name: pacemaker_common
        tasks_from: elect_active_node
      run_once: true

    - name: "Validate Election Success"
      ansible.builtin.fail:
        msg: "No active cluster node could be determined. Aborting."
      when: active_cluster_node is not defined or active_cluster_node == ""

  tasks:
    - name: Disable the Web Server resource
      include_role:
        name: pcs_cluster_resource_state
      when: inventory_hostname == active_cluster_node
      vars:
        pcs_resource_name: "web"
        pcs_resource_state: "disabled"

    - name: Perform maintenance task
      ansible.builtin.debug:
        msg: "Performing maintenance while resource is down..."

    - name: Enable the Web Server resource
      include_role:
        name: pcs_cluster_resource_state
      when: inventory_hostname == active_cluster_node
      vars:
        pcs_resource_name: "web"
        pcs_resource_state: "enabled"
        pcs_wait_retries: 60 # Increase wait time for startup
